### ISSUE TITLE
Could not resolve various .js files

### ISSUE THREAD

**Issue by heywoodlh** [vrtmrz/filesystem-livesync#6]
When running the latest version of the Dockerfile, exactly as before, the application fails:

```
> filesystem-livesync@0.0.1 dev
> node esbuild.config.mjs && node dist/index.js

Error: Build failed with 3 errors:
src/index.ts:15:97: ERROR: Could not resolve "./lib/src/utils.js"
src/index.ts:16:122: ERROR: Could not resolve "./lib/src/types.js"
src/index.ts:17:25: ERROR: Could not resolve "./lib/src/LRUCache.js"
    at failureErrorWithLog (/app/node_modules/esbuild/lib/main.js:1602:15)
    at /app/node_modules/esbuild/lib/main.js:1248:28
    at runOnEndCallbacks (/app/node_modules/esbuild/lib/main.js:1161:65)
    at buildResponseToResult (/app/node_modules/esbuild/lib/main.js:1246:7)
    at /app/node_modules/esbuild/lib/main.js:1355:14
    at /app/node_modules/esbuild/lib/main.js:665:9
    at handleIncomingPacket (/app/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/app/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "./lib/src/utils.js"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "./lib/src/types.js"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "./lib/src/LRUCache.js"'
    }
  ],
  warnings: []
}
```

Here's how I'm invoking the container:

```
#!/usr/bin/env bash

cur_dir=${PWD##*/}
docker run --name=obsidian-${cur_dir} -d -e CHOKIDAR_USEPOLLING=1 -v $(pwd):/data heywoodlh/filesystem-livesync
```

The older container version `2022_04` works just fine, with the exact same configuration. This makes me think there is a node dependency that is having an issue in the project.

Any ideas as to what is broken? For now, I have no issue just continuing to use the 2022_04 tag.

**Comment by vrtmrz** [comment]
Thank you for asking me!
The major change from that point was common functions were extracted into submodules.
Therefore, we have to clone this repository recursively or update submodules by `git submodule init && git submodule update`.
Additionally, this repo has been a bit outdated (even though still compatible). I will update this later!
